spring:
  application:
    name: csms

  datasource:
    url: jdbc:mysql://localhost:3306/csmsshop?useSSL=false&serverTimezone=UTC
    username: root
    password: 451070
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080



