-- V1_0__initial_schema.sql
-- Base schema for Computer Spare Parts Management System

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    email VARCHAR(100),
    role VARCHAR(20),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    parent_id BIGINT,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category_id BIGINT,
    sku VARCHAR(50) UNIQUE,
    price DECIMAL(10,2),
    stock_quantity INT DEFAULT 0,
    reorder_level INT DEFAULT 10,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- Insert default user
INSERT INTO users (username, password, full_name, email, role)
VALUES ('admin', 'admin123', 'System Administrator', 'admin@csms.com', 'ADMIN');

-- Insert default categories
INSERT INTO categories (name, description) VALUES
    ('CPU', 'Processors and CPUs'),
    ('Motherboard', 'Motherboards'),
    ('RAM', 'Memory modules'),
    ('Storage', 'Hard drives and SSDs'),
    ('GPU', 'Graphics cards'),
    ('PSU', 'Power supplies'),
    ('Cooling', 'Cooling systems'),
    ('Peripherals', 'Keyboards, mice, monitors');
