-- V1.2__sales_schema.sql
-- Schema for Sales Transactions

CREATE TABLE IF NOT EXISTS sales_transactions (
                                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  transaction_date TIMESTAMP NOT NULL,
                                                  amount DECIMAL(10,2) NOT NULL,
                                                  customer_name VARCHAR(100) NOT NULL,
                                                  description VARCHAR(255),
                                                  payment_method VARCHAR(50) NOT NULL,
                                                  status VARCHAR(20) NOT NULL,
                                                  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                  last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);